version: '3.8'

services:
  db:
    image: mongo:latest

  mongo-express:
    image: mongo-express
    ports:
      - "8888:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env.example
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--spider", "http://api:3000/health"]
      interval: 10s
      timeout: 15s  
      retries: 3

